#set global RUN_MODE = "DEV" // just something I like to add to scripts in case I want to run things differently during development or debugging

set yourDaiServerUrl = "xx.xx.xx.xx" //"uat.dai.webperfdev.com" //OR IP ADDRESS
set global DAIServer = !"https://[[yourDaiServerUrl]]"//do not include port 8000

// these are used by GetAccessToken to set global access_token when it has not already been set manually
set global DAIClientID = "client:dai:api:integration:xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
set global DAIClientSecret = "SecretCodeGeneneratedByDAI"

// if you manually set the global access_token then DaiApi won't try to use GetAccessToken
// this can be used to simplify troubleshooting or development
set global access_token = empty
set global expiresAt = yesterday